insert into public.plans (id, name, price_monthly, price_yearly, max_people, max_admins, whatsapp_enabled, export_enabled, future_tree_enabled)
values
  ('11111111-1111-4111-8111-111111111111', 'Basic Family', 99, 999, 50, 1, false, false, false),
  ('22222222-2222-4222-8222-222222222222', 'Family Plus', 199, 1999, 250, 3, false, true, true),
  ('33333333-3333-4333-8333-333333333333', 'Premium Family', 399, 3999, 1000, 10, true, true, true)
on conflict (id) do update set
  name = excluded.name,
  price_monthly = excluded.price_monthly,
  price_yearly = excluded.price_yearly,
  max_people = excluded.max_people,
  max_admins = excluded.max_admins,
  whatsapp_enabled = excluded.whatsapp_enabled,
  export_enabled = excluded.export_enabled,
  future_tree_enabled = excluded.future_tree_enabled;

insert into public.relationship_types (workspace_id, name, category, inverse_name, tree_mapping, is_system_default)
values
  (null, 'Father', 'Immediate Family', 'Child', 'parent', true),
  (null, 'Mother', 'Immediate Family', 'Child', 'parent', true),
  (null, 'Son', 'Immediate Family', 'Parent', 'child', true),
  (null, 'Daughter', 'Immediate Family', 'Parent', 'child', true),
  (null, 'Brother', 'Immediate Family', 'Sibling', 'sibling', true),
  (null, 'Sister', 'Immediate Family', 'Sibling', 'sibling', true),
  (null, 'Husband', 'Immediate Family', 'Wife', 'spouse', true),
  (null, 'Wife', 'Immediate Family', 'Husband', 'spouse', true),
  (null, 'Spouse', 'Immediate Family', 'Spouse', 'spouse', true),
  (null, 'Grandfather', 'Grandparents', 'Grandchild', 'none', true),
  (null, 'Grandmother', 'Grandparents', 'Grandchild', 'none', true),
  (null, 'Paternal Grandfather', 'Grandparents', 'Grandchild', 'none', true),
  (null, 'Paternal Grandmother', 'Grandparents', 'Grandchild', 'none', true),
  (null, 'Maternal Grandfather', 'Grandparents', 'Grandchild', 'none', true),
  (null, 'Maternal Grandmother', 'Grandparents', 'Grandchild', 'none', true),
  (null, 'Grandson', 'Grandchildren', 'Grandparent', 'none', true),
  (null, 'Granddaughter', 'Grandchildren', 'Grandparent', 'none', true),
  (null, 'Grandchild', 'Grandchildren', 'Grandparent', 'none', true),
  (null, 'Paternal Uncle', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Paternal Aunt', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Father''s Brother', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Father''s Sister', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Chacha', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Chachi', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Fui', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Fua', 'Father''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Maternal Uncle', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Maternal Aunt', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Mother''s Brother', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Mother''s Sister', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Mama', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Mami', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Masi', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Masa', 'Mother''s Side', 'Nephew/Niece', 'none', true),
  (null, 'Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'Male Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'Female Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'Paternal Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'Maternal Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'First Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'Second Cousin', 'Cousins', 'Cousin', 'none', true),
  (null, 'Father-in-law', 'In-Laws', 'Child-in-law', 'none', true),
  (null, 'Mother-in-law', 'In-Laws', 'Child-in-law', 'none', true),
  (null, 'Son-in-law', 'In-Laws', 'Parent-in-law', 'none', true),
  (null, 'Daughter-in-law', 'In-Laws', 'Parent-in-law', 'none', true),
  (null, 'Brother-in-law', 'In-Laws', 'Sibling-in-law', 'none', true),
  (null, 'Sister-in-law', 'In-Laws', 'Sibling-in-law', 'none', true),
  (null, 'Co-sister', 'In-Laws', 'Co-sister', 'none', true),
  (null, 'Co-brother', 'In-Laws', 'Co-brother', 'none', true),
  (null, 'Great Grandfather', 'Extended Family', 'Great Grandchild', 'none', true),
  (null, 'Great Grandmother', 'Extended Family', 'Great Grandchild', 'none', true),
  (null, 'Great Grandson', 'Extended Family', 'Great Grandparent', 'none', true),
  (null, 'Great Granddaughter', 'Extended Family', 'Great Grandparent', 'none', true),
  (null, 'Great Uncle', 'Extended Family', 'Relative', 'none', true),
  (null, 'Great Aunt', 'Extended Family', 'Relative', 'none', true),
  (null, 'Nephew', 'Extended Family', 'Uncle/Aunt', 'none', true),
  (null, 'Niece', 'Extended Family', 'Uncle/Aunt', 'none', true),
  (null, 'Uncle', 'Extended Family', 'Nephew/Niece', 'none', true),
  (null, 'Aunt', 'Extended Family', 'Nephew/Niece', 'none', true),
  (null, 'Relative', 'Extended Family', 'Relative', 'none', true),
  (null, 'Elder', 'Extended Family', 'Relative', 'none', true),
  (null, 'Family Friend', 'Extended Family', 'Family Friend', 'none', true),
  (null, 'Stepfather', 'Step / Adoptive', 'Stepchild', 'parent', true),
  (null, 'Stepmother', 'Step / Adoptive', 'Stepchild', 'parent', true),
  (null, 'Stepson', 'Step / Adoptive', 'Stepparent', 'child', true),
  (null, 'Stepdaughter', 'Step / Adoptive', 'Stepparent', 'child', true),
  (null, 'Stepbrother', 'Step / Adoptive', 'Stepsibling', 'sibling', true),
  (null, 'Stepsister', 'Step / Adoptive', 'Stepsibling', 'sibling', true),
  (null, 'Adoptive Father', 'Step / Adoptive', 'Adopted Child', 'parent', true),
  (null, 'Adoptive Mother', 'Step / Adoptive', 'Adopted Child', 'parent', true),
  (null, 'Adopted Son', 'Step / Adoptive', 'Adoptive Parent', 'child', true),
  (null, 'Adopted Daughter', 'Step / Adoptive', 'Adoptive Parent', 'child', true),
  (null, 'Guardian', 'Step / Adoptive', 'Ward', 'none', true),
  (null, 'Ward', 'Step / Adoptive', 'Guardian', 'none', true),
  (null, 'Friend', 'Friends / Community', 'Friend', 'none', true),
  (null, 'Close Friend', 'Friends / Community', 'Close Friend', 'none', true),
  (null, 'Family Friend', 'Friends / Community', 'Family Friend', 'none', true),
  (null, 'Neighbour', 'Friends / Community', 'Neighbour', 'none', true),
  (null, 'Teacher', 'Friends / Community', 'Student', 'none', true),
  (null, 'Student', 'Friends / Community', 'Teacher', 'none', true),
  (null, 'Mentor', 'Friends / Community', 'Mentee', 'none', true),
  (null, 'Colleague', 'Friends / Community', 'Colleague', 'none', true),
  (null, 'Community Member', 'Friends / Community', 'Community Member', 'none', true),
  (null, 'Jamaat Member', 'Friends / Community', 'Jamaat Member', 'none', true)
on conflict (workspace_id, name) do nothing;
